### ISSUE TITLE
Code2Pdf error when convert the source files

### ISSUE THREAD

**Issue by grazielegs** [lucascaton/code2pdf#12]
Hi!

I install Ruby with RVM and code2pdf lib, but when I execute the command, I get this error:

```

/root/.rvm/gems/ruby-2.1.10/gems/code2pdf-0.4.2/lib/code2pdf/convert_to_pdf.rb:1                                 14:in `gsub': invalid byte sequence in UTF-8 (ArgumentError)
        from /root/.rvm/gems/ruby-2.1.10/gems/code2pdf-0.4.2/lib/code2pdf/conver                                 t_to_pdf.rb:114:in `prepare_line_breaks'
        from /root/.rvm/gems/ruby-2.1.10/gems/code2pdf-0.4.2/lib/code2pdf/conver                                 t_to_pdf.rb:37:in `block in pdf'
        from /root/.rvm/gems/ruby-2.1.10/gems/code2pdf-0.4.2/lib/code2pdf/conver                                 t_to_pdf.rb:35:in `each'
        from /root/.rvm/gems/ruby-2.1.10/gems/code2pdf-0.4.2/lib/code2pdf/conver                                 t_to_pdf.rb:35:in `pdf'
        from /root/.rvm/gems/ruby-2.1.10/gems/code2pdf-0.4.2/lib/code2pdf/conver                                 t_to_pdf.rb:27:in `save'
        from /root/.rvm/gems/ruby-2.1.10/gems/code2pdf-0.4.2/lib/code2pdf/conver                                 t_to_pdf.rb:20:in `initialize'
        from /root/.rvm/gems/ruby-2.1.10/gems/code2pdf-0.4.2/bin/code2pdf:39:in                                  `new'
        from /root/.rvm/gems/ruby-2.1.10/gems/code2pdf-0.4.2/bin/code2pdf:39:in                                  `<top (required)>'
        from /root/.rvm/gems/ruby-2.1.10/bin/code2pdf:23:in `load'
        from /root/.rvm/gems/ruby-2.1.10/bin/code2pdf:23:in `<main>'
        from /root/.rvm/gems/ruby-2.1.10/bin/ruby_executable_hooks:15:in `eval'
        from /root/.rvm/gems/ruby-2.1.10/bin/ruby_executable_hooks:15:in `<main>    
```

It's my first time using this lib. How I can proceed? 

Thank you.

**Comment by lucascaton** [comment]
Hi @grazielegs, the files you're loading must be in UTF-8 encoding :)

**Comment by grazielegs** [comment]
Ah, right! That's strange cause I test my personal Java projects last night and all are default in UTF-8 but returned a error missing the gem "wkhtmltopdf" even there aren't html files haha.
I'm actually testing your lib in my work. I'll check the encoding of the projects and if I get any progress, I'm going to update that issue :smile:

**Comment by lucascaton** [comment]
Hi @grazielegs - `wkhtmltopdf` is internally used by `code2pdf` because it writes a HTML file and convertes it to a PDF :)
