### ISSUE TITLE
UTF-8 error

### ISSUE THREAD

**Issue by fortunto2** [lucascaton/code2pdf#13]
Hi, thanks for app. But i got error with russia words:
```
Reading file ./microservices/transcoding_to_360/consumer_echo.py
/var/lib/gems/2.3.0/gems/code2pdf-0.4.2/lib/code2pdf/convert_to_pdf.rb:114:in `gsub': invalid byte sequence in UTF-8 (ArgumentError)
	from /var/lib/gems/2.3.0/gems/code2pdf-0.4.2/lib/code2pdf/convert_to_pdf.rb:114:in `prepare_line_breaks'
	from /var/lib/gems/2.3.0/gems/code2pdf-0.4.2/lib/code2pdf/convert_to_pdf.rb:37:in `block in pdf'
	from /var/lib/gems/2.3.0/gems/code2pdf-0.4.2/lib/code2pdf/convert_to_pdf.rb:35:in `each'
	from /var/lib/gems/2.3.0/gems/code2pdf-0.4.2/lib/code2pdf/convert_to_pdf.rb:35:in `pdf'
	from /var/lib/gems/2.3.0/gems/code2pdf-0.4.2/lib/code2pdf/convert_to_pdf.rb:27:in `save'
	from /var/lib/gems/2.3.0/gems/code2pdf-0.4.2/lib/code2pdf/convert_to_pdf.rb:20:in `initialize'
	from /var/lib/gems/2.3.0/gems/code2pdf-0.4.2/bin/code2pdf:39:in `new'
	from /var/lib/gems/2.3.0/gems/code2pdf-0.4.2/bin/code2pdf:39:in `<top (required)>'
	from /usr/local/bin/code2pdf:22:in `load'
	from /usr/local/bin/code2pdf:22:in `<main>'
```

**Comment by lucascaton** [comment]
Hi @fortunto2. This gem supports `UTF-8` only.

**Comment by fortunto2** [comment]
me help
`iconv -f ISO-8859-1  -t UTF-8 ./microservices/segmenting/models.py > test.py`

**Comment by lucascaton** [comment]
Thanks @fortunto2! 😄
