### ISSUE TITLE
Is Something Missing? 

### ISSUE THREAD

**Issue by betoflakes** [lucascaton/code2pdf#23]
Mac OS 10.15.4
Trying to convert a ReactJS project. just src directory.

What did I made wrong?

```console
Traceback (most recent call last):
        10: from /usr/local/bin/code2pdf:23:in `<main>'
         9: from /usr/local/bin/code2pdf:23:in `load'
         8: from /Library/Ruby/Gems/2.6.0/gems/code2pdf-0.4.3/bin/code2pdf:39:in `<top (required)>'
         7: from /Library/Ruby/Gems/2.6.0/gems/code2pdf-0.4.3/bin/code2pdf:39:in `new'
         6: from /Library/Ruby/Gems/2.6.0/gems/code2pdf-0.4.3/lib/code2pdf/convert_to_pdf.rb:23:in `initialize'
         5: from /Library/Ruby/Gems/2.6.0/gems/code2pdf-0.4.3/lib/code2pdf/convert_to_pdf.rb:30:in `save'
         4: from /Library/Ruby/Gems/2.6.0/gems/code2pdf-0.4.3/lib/code2pdf/convert_to_pdf.rb:38:in `pdf'
         3: from /Library/Ruby/Gems/2.6.0/gems/code2pdf-0.4.3/lib/code2pdf/convert_to_pdf.rb:38:in `each'
         2: from /Library/Ruby/Gems/2.6.0/gems/code2pdf-0.4.3/lib/code2pdf/convert_to_pdf.rb:40:in `block in pdf'
         1: from /Library/Ruby/Gems/2.6.0/gems/code2pdf-0.4.3/lib/code2pdf/convert_to_pdf.rb:118:in `prepare_line_breaks'
/Library/Ruby/Gems/2.6.0/gems/code2pdf-0.4.3/lib/code2pdf/convert_to_pdf.rb:118:in `gsub': invalid byte sequence in US-ASCII (ArgumentError)


//Separated errors
Traceback (most recent call last):
        9: from /usr/local/bin/code2pdf:23:in `<main>'
        8: from /usr/local/bin/code2pdf:23:in `load'
        7: from /Library/Ruby/Gems/2.6.0/gems/code2pdf-0.4.3/bin/code2pdf:39:in `<top (required)>'
        6: from /Library/Ruby/Gems/2.6.0/gems/code2pdf-0.4.3/bin/code2pdf:39:in `new'
        5: from /Library/Ruby/Gems/2.6.0/gems/code2pdf-0.4.3/lib/code2pdf/convert_to_pdf.rb:23:in `initialize'
        4: from /Library/Ruby/Gems/2.6.0/gems/code2pdf-0.4.3/lib/code2pdf/convert_to_pdf.rb:30:in `save'
        3: from /Library/Ruby/Gems/2.6.0/gems/code2pdf-0.4.3/lib/code2pdf/convert_to_pdf.rb:44:in `pdf'
        2: from /Library/Ruby/Gems/2.6.0/gems/code2pdf-0.4.3/lib/code2pdf/convert_to_pdf.rb:44:in `new'
        1: from /Library/Ruby/Gems/2.6.0/gems/pdfkit-0.8.4.2/lib/pdfkit/pdfkit.rb:36:in `initialize'
/Library/Ruby/Gems/2.6.0/gems/pdfkit-0.8.4.2/lib/pdfkit/pdfkit.rb:94:in `find_options_in_meta': uninitialized constant PDFKit::Tempfile (NameError)
```

**Comment by stvhuang** [comment]
+1, I met the same lower part error.

on both macOS 10.14 and ArchLinux with Ruby 2.7.0.

Edit: Solved by downgrading `pdfkit` to 0.8.4.

**Comment by e105-gamma** [comment]
Don't help :(

	9: from /usr/local/bin/code2pdf:23:in `<main>'
	8: from /usr/local/bin/code2pdf:23:in `load'
	7: from /var/lib/gems/2.7.0/gems/code2pdf-0.4.3/bin/code2pdf:39:in `<top (required)>'
	6: from /var/lib/gems/2.7.0/gems/code2pdf-0.4.3/bin/code2pdf:39:in `new'
	5: from /var/lib/gems/2.7.0/gems/code2pdf-0.4.3/lib/code2pdf/convert_to_pdf.rb:23:in `initialize'
	4: from /var/lib/gems/2.7.0/gems/code2pdf-0.4.3/lib/code2pdf/convert_to_pdf.rb:30:in `save'
	3: from /var/lib/gems/2.7.0/gems/code2pdf-0.4.3/lib/code2pdf/convert_to_pdf.rb:44:in `pdf'
	2: from /var/lib/gems/2.7.0/gems/code2pdf-0.4.3/lib/code2pdf/convert_to_pdf.rb:44:in `new'
	1: from /var/lib/gems/2.7.0/gems/pdfkit-0.8.4.2/lib/pdfkit/pdfkit.rb:36:in `initialize'
/var/lib/gems/2.7.0/gems/pdfkit-0.8.4.2/lib/pdfkit/pdfkit.rb:94:in `find_options_in_meta': uninitialized constant PDFKit::Tempfile (NameError)

Ubuntu Focal
